name: surf_logger
version: 2.0.0
description: "Production-level logger for Dart & Flutter"
repository: "https://github.com/surfstudio/flutter-surf-logger"
issue_tracker: "https://github.com/surfstudio/flutter-surf-logger/issues"

dev_dependencies:
  mocktail: ^0.3.0
  lints: ^2.0.1
  test: ^1.16.8

environment:
  sdk: ">=3.0.0 <4.0.0"
