name: surf_logger
version: 1.0.2
description: "Logger for Dart & Flutter"
repository: "https://github.com/surfstudio/flutter-surf-logger"
issue_tracker: "https://github.com/surfstudio/flutter-surf-logger/issues"

dependencies:
  logger: ^1.0.0

dev_dependencies:
  mocktail: ^0.1.1
  surf_lint_rules: ^1.0.0
  test: ^1.16.0

environment:
  sdk: ">=2.12.0 <3.0.0"
